// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

com.aiagents.data.model.Conversation
com.aiagents.data.model.MessageNode
com.aiagents.ai.ui.UIMessage
com.aiagents.ai.ui.UIMessageChoice
com.aiagents.ai.ui.MessageChunk
com.aiagents.ai.ui.UIMessageAnnotation
com.aiagents.ai.ui.ToolApprovalState
com.aiagents.ai.core.TokenUsage